# -*- coding: utf-8 -*-
"""jerena_hw6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qthVvP56nhEQYbH6-AdckVGQK34Fdade
"""

#Annagurbanova Jeren
coursesfile = input("Please enter filename for the courses list: ")
finalsfile = input("Please enter filename for the finals list: ")
infilec = open(coursesfile, "r")
infilef = open(finalsfile, "r")

mydict = {}

#creating the dictionary
for line in infilec:
  line = line.strip()
  line = line.split(" ")
  stuID = line[0]
  if stuID in mydict:
     for i in range(1, len(line)):
       mydict[stuID].append(line[i])
  else:
      courselist = []
      for i in range(1, len(line)):
        courselist.append(line[i])
      mydict[stuID] = courselist

#getting the student id from the user and finding the student from the dictionary
myList = []
getid = False

while  getid == False:
  studentid = input ("Please enter a student ID: ")
  for i in mydict:
    if i == studentid:
      myList = mydict[i] ######################%############################xdid here we takethe courses of tte student 
      getid = True
  if getid == False:
    print("There is no student with ID", studentid)
#getting finals info
all_courses = []

for line in infilef:
  line = line.strip()
  line = line.split("\t")
  if line[0] in myList:  # myList is here the name of the courses the student is taking 
    each_course_details =[]  
    for i in range(0, len(line)):  
      each_course_details.append(line[i])   ###### is it like creating schedule of the courses spesific to the student adding EVEN the course name
    all_courses.append(each_course_details)  ####### nested lists with the courses information 
#sorting dates
listofdates = []
for i in all_courses:
  listofdates.append(i[2])
listofdates.sort()

#creating a dictioanary with a key date and a value list of timings
dates = {}
time =[]
for date in listofdates:   ### listofdates-yn ichinde sorted dates-lar bar
  for course in all_courses:
    if date in course:
      if date in dates:
        if course[3] not in dates[date]:  ###### BU nye lazim????????????????????????????/ ne yapiyo yaniiii 
          dates[date].append(course[3])
      else:
          dates[date] = [course[3]]
for d in dates:
  dates[d].sort()

#displaying exam schedule
print("Final exam schedule of student with ID", studentid+":")
has_been = []
for date in listofdates:
    if len(dates[date])== 1:
      for a in all_courses:
        if a[2] == date and a[3] in dates[date]: 
          print(a[1], a[2], a[3], sep= "\t" )
    else:
      for i in dates[date]:
        for b in all_courses:
          if b[2] == date:
            if b[3] == i:
              if b[2]+b[3] not in has_been:
                print(b[1], b[2], b[3], sep= "\t" )
                has_been.append(b[2]+b[3])
                break


#courses that have no finals
no_exams = ""
no = True
for i in myList:
  no = True
  for a in all_courses:   
    if i in a:
      no = False
      break 
  if no == True:   
    no_exams+= i+", "
no_exams = no_exams[:-2]
if no_exams != "":        
  print("Courses without a final exam:",no_exams)
