# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1adTl6Tgoic9FaErvoCZteaPOECz0suhY
"""

product_name = []
purchase_years = []
input1 = input("Products and their purchasing dates: ")
input1_split = input1.split(",")
for y in input1_split:    #in this loop new lists for product name and the year they were purhased is created
  us = y.index("_")
  proname = y[:us]  
  pyear = y[-4:]     
  product_name.append(proname)    # list for product names 
  purchase_years.append(pyear)    #list for the year the products were purchased
input2 = input("Prices of the products: ") 
input2_split = input2.split(",")    #list for the separate prices of the product
input3 = input("Starting Year-Ending Year: ")   
n = True 

while n == True:       #loop that checks the correctness of the year intervals entered
  if input3.count("-") == 1:
    year_int = input3.split("-")
    if (year_int[0].isdigit() == True) and (len(year_int[0]) == 4):
      if year_int[0] <= year_int[1]:
        n = False
        break                                       ############### shu break name uchin ishleya?????? if dan chykyamy ya while-dan chykyamy ////////////////////////////////
  print("Years were not entered in correct format.")       
  input3 = input("Starting Year-Ending Year: ")

input4 = input("Product Name: ")
while input4 not in product_name:   # loop to check if the entered product is present in the original previous list of products 
  print ("The customer did not buy this product.")
  input4 = input("Product Name: ")
  
newList_product = []
newList_price = []
newList_year = []
totalPrice = 0

while input4 in product_name:  #loop that collects information about the product (its name, its prices and purchased years)
  index_of_input4 = product_name.index(input4)
  newList_product.append(input4)
  newList_price.append(input2_split[index_of_input4])
  newList_year.append(purchase_years[index_of_input4])
  product_name.remove(input4)
  input2_split.remove(input2_split[index_of_input4])
  purchase_years.remove(purchase_years[index_of_input4])

interval_year_list = []
for i in range(int(year_int[0]),int(year_int[1])+1): #loop that makes the list of the years of that interval   ex: interval = 8-14 ici-> 8 9 10 11 12 13 14
  interval_year_list.append(i) 

for i in range(len(interval_year_list)):     ###loop that calculates the total price of the product during interested years ex i = 0 1 2 3 4 5 6 for 8 9 10 11 12 13 14
  for a in range(len(newList_year)):  ### ex: 8 11 14 bbb  0 1 2 
    while interval_year_list[i] == int(newList_year[a]):
      totalPrice+= float(newList_price[a])
      newList_price[a]="0"      
      newList_year[a] = "0"

      
print("Customer spent ", totalPrice," for ", input4, " in years ", input3, ".", sep = "")
