# -*- coding: utf-8 -*-
"""jerena_hw3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WlztKP6YFyB-Ioi6J0fzglKxuZl9urxn
"""

"""
Jeren Annagurbanova 
28517   
Take-Home Exam #3   21/04/2019-30/06/1979

"""
overall_score = 0  # initial overall score
checker = 0  # counts the errors 
dates = input("Today's date and your birth date: ") #taking input date from the user
dash = dates.find("-")    #looking for dash's index in the input string
birthYear = int (dates[len(dates) - 4 : ])  #birthyear is the last 4 digits of the string 
applyYear = int(dates[dash - 4 : dash])   #application year is 4 digits before the dash   
age = applyYear - birthYear       
age_score = age * 0.4    #scores gained by age              

job_p = input("The position you are applying for: ")   #getting input for profession name
job_p = job_p.capitalize() 

###### L A W Y E R #######     
     
if job_p == "Lawyer" :  #if the job input is a lawyer
  num_cases =input("How many cases did you work on?: ")  #ask for number of grades
  if num_cases.isalnum():   # checks for non-existence of special characters , so that input is not float                         
    if num_cases.isdigit():  #checks whether it is an integer                          
      num_cases = int(num_cases)                        
      if num_cases >= 10 :                              
        num_of_success = int(input("The number of your successful cases: ")) 
        points_for_successful = num_of_success * 5 #points for successful cases                       
        points_for_unsuccessful = (num_cases - num_of_success) * 2 #points for unsuccessful cases         
        points_for_case = points_for_successful  - points_for_unsuccessful   #overall points gained for cases
      elif num_cases < 10 and num_cases > 0:            
        points_for_case = num_cases * 3        # points gained if  number of cases  r less than 10         
      else:
        points_for_case = 0                                                                  
      overall_score  = points_for_case + age_score #overall point calculation for lawyer
    else:
      print("Error: You did not enter an integer.")
      checker += 1 #added error
  else:
    print("Error: You did not enter an integer.")
    checker += 1  #added error 
  


####### S O F T W A R E  D E V E L O P E R ########

elif job_p == "Software developer":
  python = input("Have you ever used Python in your projects?: ")  
  python = python.capitalize()            
  if python != "Yes" and python != "No": # checks whether input "python" is right or not
    print("Error: Invalid answer for using Python.")
    checker += 1 
  else:              # checks if applicant used python or not
    if python == "Yes":                    
      score = 40
    if python == "No":                    
      score = 15
    overall_score  = score + age_score         #calculates the overall score gained by software developer        
    
########### F A C U L T Y  M E M B E R ##########
elif job_p == "Faculty member" :
  f_m_number = input("Experience, number of conference and journal papers (E-C-J): ")
  f_m_number = f_m_number.split("-") #splits string faculty member string and makes a list 
  experience = float(f_m_number[0]) * 0.7  #calculates points for experience
  conference = float(f_m_number[1]) * 1.5  #calculates points for conference 
  j_paper = float(f_m_number[2]) * 2.5     #calculates points journal papers
  score_of_f_mem = experience + conference + j_paper
  overall_score = score_of_f_mem + age_score         
############## N O N E ############### 
else :
  print ("Error: No such jobs available.")
  checker += 1   
#if there is no errors then displays the overall scores 
if checker == 0:   
  if overall_score <= 40 :
    print ("Your score is", format (overall_score, ".2f"), "and your interview will be on 13/11/2019.")
  elif overall_score <= 70:
    print ("Your score is", format (overall_score, ".2f"), "and your interview will be on 12/11/2019.")
  elif overall_score > 70:
    print ("Your score is", format (overall_score, ".2f"), "and your interview will be on 11/11/2019.")

