# -*- coding: utf-8 -*-
"""jerena_hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18T6v60LWeikz4l43MZ9tfI3V0O2GjN0R
"""

"""""""""""""""""""""""""""""
"Take-Home Exam             "
"Author: Jeren Annagurbanova"
"IDE: Google_CoLab          "
"Course: IF-100             "
"Deadline: 25 October, 2019 "
"""""""""""""""""""""""""""""

# getting input values from the user 

take_off_vel = int(input("Please enter the average take-off velocity (m/s): ")) 
flight_vel = int(input("Please enter the average flight velocity (m/s): ")) 
landing_vel = int(input("Please enter the average landing velocity (m/s): "))

e_orbit = 300    # distance in kilometers from Earth's surface to the Earth's orbit 
m_orbit = 384400 # distance in kilometers from Earth's orbit to the Moon's orbit
m_land = 100     # distance in kilometers from the Moon's orbit to the Moon's surface
                                           
time1 = (e_orbit * 1000) / take_off_vel # time needed to reach Earth's orbit
time2 = (m_orbit * 1000) / flight_vel # time needed to reach Moon's orbit
time3 = (m_land * 1000) / landing_vel # time needed to reach Moon's surface

t_time = time1 + time2 + time3 # total time needed to complete the mission

# converting to day(s) : hour(s) : minut(s) : second(s) scale

s = t_time % 60            #seconds
m = (t_time / 60) % 60     #minutes
h = (t_time /60) / 60 % 24 #hours
d = (t_time /60) / 60 / 24 #days
  
  
m = "The mission will take " + str(int(d)) + " day(s), " + str(int(h)) + " hour(s), " + str(int(m)) + " minute(s), " + str(format(s, ".2f")) + " second(s)."
print(m)
